import {
  AppWindow,
  Bookmark,
  BookOpen,
  Box,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleHelp,
  Clipboard,
  Code2,
  Copy,
  Database,
  Download,
  Edit2,
  ExternalLink,
  File,
  FileDown,
  Folder,
  Globe,
  GripVertical,
  Heart,
  Home,
  Image,
  LayoutGrid,
  Lightbulb,
  List,
  LocateFixed,
  Lock,
  Moon,
  Music2,
  Paintbrush,
  Palette,
  PanelTop,
  Pin,
  PinOff,
  Plus,
  Redo2,
  RotateCcw,
  Search,
  Settings,
  SlidersHorizontal,
  Star,
  StarOff,
  Sun,
  Trash2,
  Undo2,
  Unlock,
  Upload,
  X,
} from 'lucide-react';
import { adaptSvgIcon, type ThemeIconPack } from './types';

const L = (Icon: Parameters<typeof adaptSvgIcon>[0]) => adaptSvgIcon(Icon, 'lucide');

/**
 * Sole product icon pack — Lucide stroke icons only.
 */
export const lucideIconPack: ThemeIconPack = {
  settings: L(Settings),
  search: L(Search),
  add: L(Plus),
  star: L(Star),
  starOff: L(StarOff),
  trash: L(Trash2),
  home: L(Home),
  box: L(Box),
  folder: L(Folder),
  document: L(File),
  clipboard: L(Clipboard),
  undo: L(Undo2),
  redo: L(Redo2),
  lock: L(Lock),
  unlock: L(Unlock),
  sun: L(Sun),
  moon: L(Moon),
  check: L(Check),
  close: L(X),
  chevronRight: L(ChevronRight),
  chevronDown: L(ChevronDown),
  database: L(Database),
  options: L(SlidersHorizontal),
  paintBrush: L(Paintbrush),
  help: L(CircleHelp),
  upload: L(Upload),
  download: L(Download),
  globe: L(Globe),
  pin: L(Pin),
  pinOff: L(PinOff),
  edit: L(Edit2),
  copy: L(Copy),
  externalLink: L(ExternalLink),
  locate: L(LocateFixed),
  image: L(Image),
  apps: L(AppWindow),
  window: L(AppWindow),
  bookmark: L(Bookmark),
  palette: L(Palette),
  rotateCcw: L(RotateCcw),
  fileDown: L(FileDown),
  fileUp: L(Upload),
  list: L(List),
  layoutGrid: L(LayoutGrid),
  collapse: L(ChevronsDownUp),
  expand: L(ChevronsUpDown),
  grip: L(GripVertical),
  packageCheck: L(CheckCircle2),
  panel: L(PanelTop),
  heart: L(Heart),
  music: L(Music2),
  book: L(BookOpen),
  idea: L(Lightbulb),
  code: L(Code2),
  briefcase: L(BriefcaseBusiness),
};
