import {
  Add20Regular,
  Apps20Regular,
  AppsList20Regular,
  ArrowCollapseAll20Regular,
  ArrowDownload20Regular,
  ArrowExpandAll20Regular,
  ArrowUndo20Regular,
  ArrowRedo20Regular,
  ArrowUpload20Regular,
  Book20Regular,
  Box20Regular,
  BoxCheckmark20Regular,
  BoxMultiple20Regular,
  Briefcase20Regular,
  Checkmark20Regular,
  ChevronDown20Regular,
  ChevronRight20Regular,
  Clipboard20Regular,
  Code20Regular,
  Color20Regular,
  Compose20Regular,
  Copy20Regular,
  Database20Regular,
  Delete20Regular,
  Dismiss20Regular,
  Document20Regular,
  Edit20Regular,
  Folder20Regular,
  Globe20Regular,
  Grid20Regular,
  Heart20Regular,
  Home20Regular,
  Image20Regular,
  Lightbulb20Regular,
  Link20Regular,
  Location20Regular,
  LockClosed20Regular,
  LockOpen20Regular,
  MusicNote220Regular,
  Open20Regular,
  Options20Regular,
  PaintBrush20Regular,
  Pin20Regular,
  PinOff20Regular,
  QuestionCircle20Regular,
  ReOrderDotsVertical20Regular,
  Search20Regular,
  Settings20Regular,
  Star20Regular,
  StarOff20Regular,
  TextBulletList20Regular,
  WeatherMoon20Regular,
  WeatherSunny20Regular,
  Window20Regular,
  WindowHeaderHorizontal20Regular,
  ArrowCounterclockwise20Regular,
} from '@fluentui/react-icons';
import { adaptSvgIcon, type ThemeIconPack } from '../types';

const F = (Icon: Parameters<typeof adaptSvgIcon>[0]) => adaptSvgIcon(Icon, 'fluent');

/** Windows Fluent — official Fluent System Icons (MIT). */
export const fluentIconPack: ThemeIconPack = {
  settings: F(Settings20Regular),
  search: F(Search20Regular),
  add: F(Add20Regular),
  star: F(Star20Regular),
  starOff: F(StarOff20Regular),
  trash: F(Delete20Regular),
  home: F(Home20Regular),
  box: F(BoxMultiple20Regular),
  folder: F(Folder20Regular),
  document: F(Document20Regular),
  clipboard: F(Clipboard20Regular),
  undo: F(ArrowUndo20Regular),
  redo: F(ArrowRedo20Regular),
  lock: F(LockClosed20Regular),
  unlock: F(LockOpen20Regular),
  sun: F(WeatherSunny20Regular),
  moon: F(WeatherMoon20Regular),
  check: F(Checkmark20Regular),
  close: F(Dismiss20Regular),
  chevronRight: F(ChevronRight20Regular),
  chevronDown: F(ChevronDown20Regular),
  database: F(Database20Regular),
  options: F(Options20Regular),
  paintBrush: F(PaintBrush20Regular),
  help: F(QuestionCircle20Regular),
  upload: F(ArrowUpload20Regular),
  download: F(ArrowDownload20Regular),
  globe: F(Globe20Regular),
  pin: F(Pin20Regular),
  pinOff: F(PinOff20Regular),
  edit: F(Edit20Regular),
  copy: F(Copy20Regular),
  externalLink: F(Open20Regular),
  locate: F(Location20Regular),
  image: F(Image20Regular),
  apps: F(Apps20Regular),
  window: F(Window20Regular),
  bookmark: F(Link20Regular),
  palette: F(Color20Regular),
  rotateCcw: F(ArrowCounterclockwise20Regular),
  fileDown: F(ArrowDownload20Regular),
  fileUp: F(ArrowUpload20Regular),
  list: F(TextBulletList20Regular),
  layoutGrid: F(Grid20Regular),
  collapse: F(ArrowCollapseAll20Regular),
  expand: F(ArrowExpandAll20Regular),
  grip: F(ReOrderDotsVertical20Regular),
  packageCheck: F(BoxCheckmark20Regular),
  panel: F(WindowHeaderHorizontal20Regular),
  heart: F(Heart20Regular),
  music: F(MusicNote220Regular),
  book: F(Book20Regular),
  idea: F(Lightbulb20Regular),
  code: F(Code20Regular),
  briefcase: F(Briefcase20Regular),
};

void Box20Regular;
void AppsList20Regular;
void Compose20Regular;
